[package]
name = "figcon"
version = "0.2.2"
description = "A small stupid-simple synchronous serde_json config manager"
license-file = "LICENSE"
repository = "https://github.com/MisterSirCode/figcon"
edition = "2024"
exclude = [
    "src/main.rs"
]

[dependencies]
serde_json = "1.0.149"
